TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += dev_NAME_.db
# FIXME -- HOW TO INSTALL _NAME_.proto????

#=======================================
include $(TOP)/configure/RULES
