dbLoadDatabase("../../dbd/test.dbd")
test_registerRecordDeviceDriver(pdbbase)

#drvGenericSerialConfigure("A","164.54.9.90:4001",0,0)
echoDriverInit("A",0.05,0,0)
interposeInterfaceInit("interpose","A",0)
echoDriverInit("B",0.05,0,1)

dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=A,addr=0")
dbLoadRecords("../../db/test.db","name=client1,port=A,addr=0")
dbLoadRecords("../../db/test.db","name=client2,port=A,addr=0")

dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=-1")
dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=0")
dbLoadRecords("../../db/test.db","name=client1,port=B,addr=0")
dbLoadRecords("../../db/test.db","name=client2,port=B,addr=0")
dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=1")
dbLoadRecords("../../db/test.db","name=client1,port=B,addr=1")
dbLoadRecords("../../db/test.db","name=client2,port=B,addr=1")
dbLoadRecords("../../db/asynGeneric.db","ioc=asynTest")
dbLoadRecords("../../db/asynOctetRecord.db","P=mrk,R=Octet,PORT=A,ADDR=0,OMAX=0,IMAX=0")
iocInit()
