TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += dev_NAME_.db
DB += dev_NAME_.proto

#=======================================
include $(TOP)/configure/RULES
