TOP=..

include $(TOP)/configure/CONFIG

TEMPLATES += devGpib/Makefile
TEMPLATES += devGpib/configure/CONFIG
TEMPLATES += devGpib/configure/CONFIG_APP
TEMPLATES += devGpib/configure/Makefile
TEMPLATES += devGpib/configure/RELEASE
TEMPLATES += devGpib/configure/RULES
TEMPLATES += devGpib/configure/RULES_DIRS
TEMPLATES += devGpib/configure/RULES_TOP
TEMPLATES += devGpib/src/Makefile
TEMPLATES += devGpib/src/dev_NAME_.c
TEMPLATES += devGpib/src/dev_NAME_.db
TEMPLATES += devGpib/src/dev_NAME_.dbd

SCRIPTS_HOST += makeSupport.pl

include $(TOP)/configure/RULES
