TOP=..

include $(TOP)/configure/CONFIG

TEMPLATES += top/Makefile
TEMPLATES += top/configure/CONFIG
TEMPLATES += top/configure/CONFIG_SITE
TEMPLATES += top/configure/Makefile
TEMPLATES += top/configure/RELEASE
TEMPLATES += top/configure/RULES
TEMPLATES += top/configure/RULES_DIRS
TEMPLATES += top/configure/RULES_TOP

TEMPLATES += devGpib/_NAME_Sup/Makefile
TEMPLATES += devGpib/_NAME_Sup/dev_NAME_.c
TEMPLATES += devGpib/_NAME_Sup/dev_NAME_.db
TEMPLATES += devGpib/_NAME_Sup/dev_NAME_.dbd
TEMPLATES += devGpib/documentation/dev_NAME_.html

TEMPLATES += app/_NAME_App/Db/Makefile
TEMPLATES += app/_NAME_App/Db/_NAME_.db
TEMPLATES += app/_NAME_App/src/Makefile
TEMPLATES += app/_NAME_App/src/_NAME_Main.cpp
TEMPLATES += app/_NAME_App/src/sncExample.stt
TEMPLATES += app/_NAME_App/Makefile

TEMPLATES += vxioc/configure/RULES.ioc
TEMPLATES += vxioc/iocBoot/_IOCNAME_/Makefile
TEMPLATES += vxioc/iocBoot/_IOCNAME_/st.cmd
TEMPLATES += vxioc/iocBoot/Makefile
TEMPLATES += vxioc/iocBoot/nfsCommands
TEMPLATES += vxioc.pl

TEMPLATES += softioc/configure/RULES.ioc
TEMPLATES += softioc/iocBoot/_IOCNAME_/Makefile
TEMPLATES += softioc/iocBoot/_IOCNAME_/README
TEMPLATES += softioc/iocBoot/_IOCNAME_/st.cmd
TEMPLATES += softioc/iocBoot/Makefile
TEMPLATES += softioc.pl

TEMPLATES += streamSCPI/_NAME_Sup/Makefile
TEMPLATES += streamSCPI/_NAME_Sup/dev_NAME_.proto
TEMPLATES += streamSCPI/_NAME_Sup/dev_NAME_.db
TEMPLATES += streamSCPI/documentation/dev_NAME_.html

SCRIPTS_HOST += makeSupport.pl

include $(TOP)/configure/RULES
