dbLoadDatabase("../../dbd/test.dbd")
test_registerRecordDeviceDriver(pdbbase)

echoDriverInit("A",0.05,0,0)
interposeInterfaceInit("interpose","A",0)
echoDriverInit("B",0.05,0,1)

dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=A,addr=0")
dbLoadRecords("../../db/test.db","name=client1,port=A,addr=0")
dbLoadRecords("../../db/test.db","name=client2,port=A,addr=0")

dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=-1")
dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=0")
dbLoadRecords("../../db/test.db","name=client1,port=B,addr=0")
dbLoadRecords("../../db/test.db","name=client2,port=B,addr=0")
dbLoadRecords("../../db/asyn.db","ioc=asynTest,port=B,addr=1")
dbLoadRecords("../../db/test.db","name=client1,port=B,addr=1")
dbLoadRecords("../../db/test.db","name=client2,port=B,addr=1")
dbLoadRecords("../../db/asynGeneric.db","ioc=asynTest")
iocInit()
