dbLoadDatabase("../../dbd/test.dbd")
test_registerRecordDeviceDriver(pdbbase)

#drvAsynIPPortConfigure("A","164.54.9.90:4001",0,0,0)
echoDriverInit("A",0.05,0,0)
interposeInterfaceInit("interpose","A",0)
echoDriverInit("B",0.05,0,1)

dbLoadRecords("../../db/asynRecord.db","P=asyn,R=Record_PA_A0,PORT=A,ADDR=0,OMAX=0,IMAX=0")
dbLoadRecords("../../db/test.db","P=test,R=Client1,PORT=A,A=0")
dbLoadRecords("../../db/test.db","P=test,R=Client2,PORT=A,A=0")

dbLoadRecords("../../db/asynRecord.db","P=asyn,R=Record_PB_A-1,PORT=B,ADDR=-1,OMAX=0,IMAX=0")
dbLoadRecords("../../db/asynRecord.db","P=asyn,R=Record_PB_A0,PORT=B,ADDR=0,OMAX=0,IMAX=0")
dbLoadRecords("../../db/test.db","P=test,R=Client1,PORT=B,A=0")
dbLoadRecords("../../db/test.db","P=test,R=Client2,PORT=B,A=0")
dbLoadRecords("../../db/asynRecord.db","P=asyn,R=Record_PB_A1,PORT=B,ADDR=1,OMAX=0,IMAX=0")
dbLoadRecords("../../db/test.db","P=test,R=Client1,PORT=B,A=1")
dbLoadRecords("../../db/test.db","P=test,R=Client2,PORT=B,A=1")
dbLoadRecords("../../db/asynRecord.db","P=asyn,R=Record,PORT=A,ADDR=0,OMAX=0,IMAX=0")
dbLoadRecords("../../db/devGenericTest.db","PORT=A,ADDR=0")
asynSetTraceMask("A",0,0xff)
asynSetTraceIOMask("A",0,0x2)
iocInit()
