TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = solaris-sparc
ARCH = linux-x86
#ARCH = cygwin-x86
#ARCH = vxWorks-ppc32
TARGETS += envPaths cdCommands dllPath.bat

include $(TOP)/configure/RULES.ioc

