# Makefile for Asyn _NAME_ support
#
# Created by _USER_ on _DATE_
# Based on the Asyn _TYPE_ template

TOP = .
include $(TOP)/configure/CONFIG

DIRS := configure
DIRS += $(wildcard *[Ss]up)
DIRS += $(wildcard *[Aa]pp)
DIRS += $(wildcard ioc[Bb]oot)

include $(TOP)/configure/RULES_TOP
