/* devAsynInt32Array.c */
/***********************************************************************
* Copyright (c) 2002 The University of Chicago, as Operator of Argonne
* National Laboratory, and the Regents of the University of
* California, as Operator of Los Alamos National Laboratory, and
* Berliner Elektronenspeicherring-Gesellschaft m.b.H. (BESSY).
* asynDriver is distributed subject to a Software License Agreement
* found in file LICENSE that is included with this distribution.
***********************************************************************/
/*
    Mark Rivers
    February 8, 2012
*/

#include "asynInt32.h"
#include "devAsynXXXTimeSeries.h"

/* The code for this driver is generated by the macro in the include file with macro substitution */

ASYN_XXX_TIME_SERIES_FUNCS("devAsynInt32TimeSeries", asynInt32, asynInt32Type,
                            interruptCallbackInt32, epicsInt32, asynInt32TimeSeries,
                            menuFtypeLONG, menuFtypeULONG)

