TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += dev_NAME_.db
DB_INSTALLS += $(TOP)/_NAME_Sup/dev_NAME_.proto

#=======================================
include $(TOP)/configure/RULES
