/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VXI11INTR_H_RPCGEN
#define _VXI11INTR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Device_SrqParms {
	struct {
		u_int handle_len;
		char *handle_val;
	} handle;
};
typedef struct Device_SrqParms Device_SrqParms;

#define DEVICE_INTR 0x0607B1
#define DEVICE_INTR_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define device_intr_srq 30
extern  void * device_intr_srq_1(Device_SrqParms *, CLIENT *);
extern  void * device_intr_srq_1_svc(Device_SrqParms *, struct svc_req *);
extern int device_intr_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define device_intr_srq 30
extern  void * device_intr_srq_1();
extern  void * device_intr_srq_1_svc();
extern int device_intr_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Device_SrqParms (XDR *, Device_SrqParms*);

#else /* K&R C */
extern bool_t xdr_Device_SrqParms ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VXI11INTR_H_RPCGEN */
